services:
    _defaults:
        public: false

    ########### Vendor services
    CoderCat\JWKToPEM\JWKConverter: ~

    GuzzleHttp\ClientInterface:
        class: GuzzleHttp\Client

    Lcobucci\JWT\Builder: ~

    Lcobucci\JWT\Parsing\Encoder: ~

    Lcobucci\JWT\Parser: ~

    Lcobucci\JWT\Signer:
        class: Lcobucci\JWT\Signer\Rsa\Sha256

    Nyholm\Psr7\Factory\Psr17Factory: ~

    League\OAuth2\Server\Repositories\AccessTokenRepositoryInterface:
        class: OAT\Library\Lti1p3Core\Service\Server\Repository\AccessTokenRepository
        arguments:
            - '@Psr\Cache\CacheItemPoolInterface'
            - '@Psr\Log\LoggerInterface'

    League\OAuth2\Server\Repositories\ClientRepositoryInterface:
        class: OAT\Library\Lti1p3Core\Service\Server\Repository\ClientRepository
        arguments:
            - '@OAT\Library\Lti1p3Core\Registration\RegistrationRepositoryInterface'
            - '@OAT\Library\Lti1p3Core\Security\Jwks\Fetcher\JwksFetcherInterface'
            - '@Psr\Log\LoggerInterface'
            - '@Lcobucci\JWT\Signer'

    League\OAuth2\Server\Repositories\ScopeRepositoryInterface:
        class: OAT\Library\Lti1p3Core\Service\Server\Repository\ScopeRepository

    OAT\Library\Lti1p3Core\Service\Server\Factory\AuthorizationServerFactory:
        arguments:
            - '@League\OAuth2\Server\Repositories\ClientRepositoryInterface'
            - '@League\OAuth2\Server\Repositories\AccessTokenRepositoryInterface'
            - '@League\OAuth2\Server\Repositories\ScopeRepositoryInterface'
            - '%env(LTI1P3_SERVICE_ENCRYPTION_KEY)%'

    Symfony\Bridge\PsrHttpMessage\HttpMessageFactoryInterface:
        class: Symfony\Bridge\PsrHttpMessage\Factory\PsrHttpFactory
        arguments:
            - '@Nyholm\Psr7\Factory\Psr17Factory'
            - '@Nyholm\Psr7\Factory\Psr17Factory'
            - '@Nyholm\Psr7\Factory\Psr17Factory'
            - '@Nyholm\Psr7\Factory\Psr17Factory'

    Symfony\Bridge\PsrHttpMessage\HttpFoundationFactoryInterface:
        class: Symfony\Bridge\PsrHttpMessage\Factory\HttpFoundationFactory

    ########### Core lib services
    OAT\Library\Lti1p3Core\Security\Key\KeyChainFactory: ~

    OAT\Library\Lti1p3Core\Platform\PlatformFactory: ~

    OAT\Library\Lti1p3Core\Tool\ToolFactory: ~

    OAT\Library\Lti1p3Core\Registration\RegistrationFactory: ~

    OAT\Library\Lti1p3Core\Security\Nonce\NonceGeneratorInterface:
        class: OAT\Library\Lti1p3Core\Security\Nonce\NonceGenerator

    OAT\Library\Lti1p3Core\Security\Nonce\NonceRepository:
        arguments:
            - '@Psr\Cache\CacheItemPoolInterface'

    OAT\Library\Lti1p3Core\Message\Token\Builder\MessageTokenBuilder:
        arguments:
            - '@OAT\Library\Lti1p3Core\Security\Nonce\NonceGeneratorInterface'
            - '@Lcobucci\JWT\Builder'
            - '@Lcobucci\JWT\Signer'

    OAT\Library\Lti1p3Core\Message\Token\Builder\MessageTokenBuilderInterface:
        class: OAT\Library\Lti1p3Core\Message\Token\Builder\MessageTokenBuilder

    ########### Bundle services
    OAT\Library\Lti1p3Core\Security\Key\KeyChainRepositoryInterface:
        alias: OAT\Library\Lti1p3Core\Security\Key\KeyChainRepository

    OAT\Library\Lti1p3Core\Security\Nonce\NonceRepositoryInterface:
        alias: OAT\Library\Lti1p3Core\Security\Nonce\NonceRepository

    OAT\Library\Lti1p3Core\Registration\RegistrationRepositoryInterface:
        alias: OAT\Bundle\Lti1p3Bundle\Repository\RegistrationRepository

    OAT\Bundle\Lti1p3Bundle\DependencyInjection\Builder\KeyChainRepositoryBuilder:
        arguments: ['@OAT\Library\Lti1p3Core\Security\Key\KeyChainFactory']

    OAT\Bundle\Lti1p3Bundle\DependencyInjection\Builder\RegistrationRepositoryBuilder:
        arguments:
            - '@OAT\Library\Lti1p3Core\Security\Key\KeyChainFactory'
            - '@OAT\Library\Lti1p3Core\Platform\PlatformFactory'
            - '@OAT\Library\Lti1p3Core\Tool\ToolFactory'
            - '@OAT\Library\Lti1p3Core\Registration\RegistrationFactory'

    OAT\Library\Lti1p3Core\Security\Jwks\Exporter\JwksExporter:
        arguments: ['@OAT\Library\Lti1p3Core\Security\Key\KeyChainRepositoryInterface']

    OAT\Library\Lti1p3Core\Security\Jwks\Server\JwksServer:
        arguments: ['@OAT\Library\Lti1p3Core\Security\Jwks\Exporter\JwksExporter']

    OAT\Library\Lti1p3Core\Security\Jwks\Fetcher\JwksFetcherInterface:
        class: OAT\Library\Lti1p3Core\Security\Jwks\Fetcher\JwksFetcher
        arguments:
            - '@Psr\Cache\CacheItemPoolInterface'
            - '@GuzzleHttp\ClientInterface'
            - '@CoderCat\JWKToPEM\JWKConverter'
            - '@Psr\Log\LoggerInterface'

    OAT\Library\Lti1p3Core\Security\Oidc\OidcInitiator:
        arguments:
            - '@OAT\Library\Lti1p3Core\Registration\RegistrationRepositoryInterface'
            - '@OAT\Library\Lti1p3Core\Security\Nonce\NonceGeneratorInterface'
            - '@OAT\Library\Lti1p3Core\Message\Token\Builder\MessageTokenBuilderInterface'

    OAT\Library\Lti1p3Core\Security\Oidc\Server\OidcInitiationServer:
        arguments: ['@OAT\Library\Lti1p3Core\Security\Oidc\OidcInitiator']

    OAT\Library\Lti1p3Core\Security\Oidc\OidcAuthenticator:
        arguments:
            - '@OAT\Library\Lti1p3Core\Registration\RegistrationRepositoryInterface'
            - '@OAT\Library\Lti1p3Core\Security\User\UserAuthenticatorInterface'
            - '@OAT\Library\Lti1p3Core\Message\Token\Builder\MessageTokenBuilderInterface'
            - '@Lcobucci\JWT\Signer'

    OAT\Library\Lti1p3Core\Security\Oidc\Server\OidcAuthenticationServer:
        arguments: ['@OAT\Library\Lti1p3Core\Security\Oidc\OidcAuthenticator']

    OAT\Library\Lti1p3Core\Message\Launch\Validator\LtiResourceLinkLaunchRequestValidator:
        arguments:
            - '@OAT\Library\Lti1p3Core\Registration\RegistrationRepositoryInterface'
            - '@OAT\Library\Lti1p3Core\Security\Nonce\NonceRepositoryInterface'
            - '@OAT\Library\Lti1p3Core\Security\Jwks\Fetcher\JwksFetcherInterface'
            - '@Lcobucci\JWT\Signer'

    OAT\Library\Lti1p3Core\Service\Server\Generator\AccessTokenResponseGenerator:
        arguments:
            - '@OAT\Library\Lti1p3Core\Security\Key\KeyChainRepositoryInterface'
            - '@OAT\Library\Lti1p3Core\Service\Server\Factory\AuthorizationServerFactory'

    OAT\Library\Lti1p3Core\Service\Server\Validator\AccessTokenRequestValidator:
        arguments:
            - '@OAT\Library\Lti1p3Core\Registration\RegistrationRepositoryInterface'
            - '@Psr\Log\LoggerInterface'
            - '@Lcobucci\JWT\Signer'

    OAT\Bundle\Lti1p3Bundle\Security\Firewall\Message\LtiMessageAuthenticationListener:
        arguments:
            - '@security.token_storage'
            - '@security.authentication.manager'
            - '@Symfony\Bridge\PsrHttpMessage\HttpMessageFactoryInterface'

    OAT\Bundle\Lti1p3Bundle\Security\Firewall\Service\LtiServiceAuthenticationListener:
        arguments:
            - '@security.token_storage'
            - '@security.authentication.manager'
            - '@Symfony\Bridge\PsrHttpMessage\HttpMessageFactoryInterface'

    OAT\Bundle\Lti1p3Bundle\Security\Authentication\Provider\Message\LtiMessageAuthenticationProvider:
        arguments:
            - '@OAT\Library\Lti1p3Core\Message\Launch\Validator\LtiResourceLinkLaunchRequestValidator'

    OAT\Bundle\Lti1p3Bundle\Security\Authentication\Provider\Service\LtiServiceAuthenticationProvider:
        arguments:
            - '@OAT\Library\Lti1p3Core\Service\Server\Validator\AccessTokenRequestValidator'

    OAT\Library\Lti1p3Core\Security\User\UserAuthenticatorInterface: ~

    OAT\Library\Lti1p3Core\Message\Launch\Builder\LtiResourceLinkLaunchRequestBuilder:
        arguments: ['@OAT\Library\Lti1p3Core\Message\Token\Builder\MessageTokenBuilderInterface']
        public: true

    OAT\Library\Lti1p3Core\Service\Client\ServiceClientInterface:
        class: OAT\Library\Lti1p3Core\Service\Client\ServiceClient
        arguments:
            - '@Psr\Cache\CacheItemPoolInterface'
            - '@GuzzleHttp\ClientInterface'
            - '@Lcobucci\JWT\Signer'
            - '@Lcobucci\JWT\Builder'
        public: true

    ########### Endpoints
    OAT\Bundle\Lti1p3Bundle\Action\Jwks\JwksAction:
        arguments:
            - '@Symfony\Bridge\PsrHttpMessage\HttpFoundationFactoryInterface'
            - '@OAT\Library\Lti1p3Core\Security\Jwks\Server\JwksServer'
        tags: ['controller.service_arguments']

    OAT\Bundle\Lti1p3Bundle\Action\Tool\Message\OidcInitiationAction:
        arguments:
            - '@Symfony\Bridge\PsrHttpMessage\HttpFoundationFactoryInterface'
            - '@Symfony\Bridge\PsrHttpMessage\HttpMessageFactoryInterface'
            - '@OAT\Library\Lti1p3Core\Security\Oidc\Server\OidcInitiationServer'
        tags: ['controller.service_arguments']

    OAT\Bundle\Lti1p3Bundle\Action\Platform\Message\OidcAuthenticationAction:
        arguments:
            - '@Symfony\Bridge\PsrHttpMessage\HttpFoundationFactoryInterface'
            - '@Symfony\Bridge\PsrHttpMessage\HttpMessageFactoryInterface'
            - '@OAT\Library\Lti1p3Core\Security\Oidc\Server\OidcAuthenticationServer'
        tags: ['controller.service_arguments']

    OAT\Bundle\Lti1p3Bundle\Action\Platform\Service\OAuth2AccessTokenCreationAction:
        arguments:
            - '@Symfony\Bridge\PsrHttpMessage\HttpFoundationFactoryInterface'
            - '@Symfony\Bridge\PsrHttpMessage\HttpMessageFactoryInterface'
            - '@OAT\Library\Lti1p3Core\Service\Server\Generator\AccessTokenResponseGenerator'
        tags: ['controller.service_arguments']
